version: 2
updates:
- package-ecosystem: cargo
  versioning-strategy: lockfile-only
  directory: "/"
  allow:
    - dependency-type: "all"
  groups:
    root-deps:
      patterns:
        - "*"
  schedule:
    interval: daily

- package-ecosystem: cargo
  versioning-strategy: lockfile-only
  directory: "validation/local_ping_pong_openssl"
  allow:
    - dependency-type: "all"
  groups:
    validation-deps:
      patterns:
        - "*"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
